# Reference: https://github.com/i3/i3/blob/next/etc/config

# i3 doesn't have "normalizations" feature that why we disable them here.
# But the feature is very helpful.
# Normalizations eliminate all sorts of weird tree configurations that don't make sense.
# Give normalizations a chance and enable them back.
enable-normalization-flatten-containers = false
enable-normalization-opposite-orientation-for-nested-containers = false

# Mouse follows focus when focused monitor changes
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

# Start AeroSpace at login
start-at-login = true

[gaps]
inner.horizontal = 6
inner.vertical =   6
outer.left =       0
outer.bottom =     0
outer.top =        0
outer.right =      0

[mode.main.binding]
# See: https://nikitabobko.github.io/AeroSpace/goodness#open-a-new-window-with-applescript
alt-enter = 'exec-and-forget ~/.local/bin/iterm-instance.sh'
#alt-enter = 'exec-and-forget ~/.local/bin/alacritty.sh'

alt-h = 'focus left'
alt-j = 'focus down'
alt-k = 'focus up'
alt-l = 'focus right'
# same with arrow keys
alt-left = 'focus left'
alt-down = 'focus down'
alt-up = 'focus up'
alt-right = 'focus right'

alt-shift-h = 'move left'
alt-shift-j = 'move down'
alt-shift-k = 'move up'
alt-shift-l = 'move right'
# same with arrow keys
alt-shift-left = 'move left'
alt-shift-down = 'move down'
alt-shift-up = 'move up'
alt-shift-right = 'move right'

# Consider using 'join-with' command as a 'split' replacement if you want to enable normalizations
alt-b = 'split horizontal'
alt-v = 'split vertical'

alt-f = 'fullscreen'

alt-s = 'layout v_accordion' # 'layout stacking' in i3
alt-w = 'layout h_accordion' # 'layout tabbed' in i3
alt-e = 'layout tiles horizontal vertical' # 'layout toggle split' in i3

alt-shift-space = 'layout floating tiling' # 'floating toggle' in i3

# Not supported, because this command is redundant in AeroSpace mental model.
# See: https://nikitabobko.github.io/AeroSpace/guide#floating-windows
#alt-space = 'focus toggle_tiling_floating'

# `focus parent`/`focus child` are not yet supported, and it's not clear whether they
# should be supported at all https://github.com/nikitabobko/AeroSpace/issues/5
# alt-a = 'focus parent'

alt-1 = 'workspace 1'
alt-2 = 'workspace 2'
alt-3 = 'workspace 3'
alt-4 = 'workspace 4'
alt-5 = 'workspace 5'
alt-6 = 'workspace 6'
alt-7 = 'workspace 7'
alt-8 = 'workspace 8'
alt-9 = 'workspace 9'
alt-0 = 'workspace 10'

alt-shift-1 = 'move-node-to-workspace 1'
alt-shift-2 = 'move-node-to-workspace 2'
alt-shift-3 = 'move-node-to-workspace 3'
alt-shift-4 = 'move-node-to-workspace 4'
alt-shift-5 = 'move-node-to-workspace 5'
alt-shift-6 = 'move-node-to-workspace 6'
alt-shift-7 = 'move-node-to-workspace 7'
alt-shift-8 = 'move-node-to-workspace 8'
alt-shift-9 = 'move-node-to-workspace 9'
alt-shift-0 = 'move-node-to-workspace 10'

alt-shift-c = 'reload-config'

alt-r = 'mode resize'
alt-shift-e = 'mode exit'

[mode.resize.binding]
h = 'resize width -50'
k = 'resize height +50'
j = 'resize height -50'
l = 'resize width +50'
left = 'resize width -50'
up= 'resize height +50'
down = 'resize height -50'
right = 'resize width +50'
enter = 'mode main'
esc = 'mode main'

[mode.exit.binding]
l = ['mode main', 'exec-and-forget pmset displaysleepnow']
s = ['mode main', 'exec-and-forget pmset sleepnow']
enter = 'mode main'
esc = 'mode main'

#############################
### Floating Window Rules ###
#############################
[[on-window-detected]]
if.app-id = 'com.apple.systempreferences'
run = ['layout floating']
[[on-window-detected]]
if.app-id = 'com.1password.1password'
run = ['layout floating']
[[on-window-detected]]
if.app-id = 'com.apple.ActivityMonitor'
run = ['layout floating']
[[on-window-detected]]
if.app-id = 'com.apple.calculator'
run = ['layout floating']
[[on-window-detected]]
if.app-id = 'com.cisco.anyconnect.gui'
run = ['layout floating']
[[on-window-detected]]
if.app-id = 'com.utmapp.UTM'
run = ['layout floating']
[[on-window-detected]]
if.app-id = 'com.microsoft.rdc.macos'
run = ['layout floating']
[[on-window-detected]]
if.app-id = 'com.apple.PhotoBooth'
run = ['layout floating']
[[on-window-detected]]
if.app-id = 'com.yubico.ykman'
run = ['layout floating']
[[on-window-detected]]
if.app-id = 'org.mozilla.thunderbird'
if.window-title-regex-substring = 'Reminder'
run = ['layout floating']
[[on-window-detected]]
if.app-id = 'org.mozilla.thunderbird'
if.window-title-regex-substring = 'Invitation'
run = ['layout floating']
